name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22'
          cache: true

      - name: Go Test
        run: |
          go test ./...