name: Go testing

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Go Test
        run: |
          go test ./...