name: Laravel testing

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  test:
    name: Redis Queue Test
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      APP_NAME: LaraQueue
      APP_KEY: abc123
      QUEUE_CONNECTION: redis
      QUEUE_FAILED_DRIVER: "null"
      TEST_CONTENT: Lorem,Ipsum

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 8s
          --health-timeout 4s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Laravel
        uses: actions/checkout@v4
        with:
          repository: 'laravel/laravel'
          ref: '11.x'
          path: 'laratest'

      - name: Setup Laravel
        run: |
            mkdir laratest/app/Jobs
            cp testscripts/laravel/LaravelTestJob.php laratest/app/Jobs/LaravelTestJob.php

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: redis
          tools: composer:v2

      - name: Install dependencies
        run: cd laratest && composer install --no-interaction --no-scripts --no-dev

      - name: Queue & Handle
        run: |
          go run testscripts/laravel/queueTest.go
          timeout 5s php laratest/artisan queue:work --once
          cat laratest/app/Jobs/foo_bar | grep "$TEST_CONTENT"

      - name: Dump Laravel logs
        if: failure()
        run: cat laratest/storage/logs/laravel.log

